### ISSUE TITLE
no attribute top_role

### ISSUE THREAD

**Issue by alec-jensen** [alec-jensen/kidney-bot#2]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/app/cogs/moderation.py", line 63, in purge
    if not await self.permissionHierarchyCheck(interaction.user, user):
  File "/app/cogs/moderation.py", line 27, in permissionHierarchyCheck
    if target.top_role >= user.top_role:
AttributeError: 'NoneType' object has no attribute 'top_role'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'purge' raised an exception: AttributeError: 'NoneType' object has no attribute 'top_role'```

**Comment by alec-jensen** [comment]
fixed in commit [30c9b73](https://github.com/alec-jensen/kidney-bot/commit/30c9b73fc384d2e530d740046a771d0d88bcf187)
